import React, { useState, useEffect } from "react";
import { createRoot } from "react-dom/client";
import Table from "./Table.jsx";

const App = () => {
  const [words, setWords] = useState("");
  const [emptyTextArea, setEmptyTextArea] = useState(false);
  const [noAlphabets, setNoAlphabets] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [autoGeneratedWords, setAutoGeneratedWords] = useState("");
  const [letterCount, setLetterCount] = useState("");
  const [sortedAlpha, setSortedByAlpha] = useState("");
  const [sortedFreq, setSortedByFreq] = useState("");

  const textProcessor = (inputString) => {
    if (!inputString) {
      // handle edge case when user leaves text area blank
      setEmptyTextArea(true);
      setLetterCount("");
    } else {
      setEmptyTextArea(false);

      let filteredLetters = inputString
        .toLowerCase()
        .split("")
        .filter((char) => /[a-z]/.test(char)); // filter out non alphabet chars

      let frequencyDictonary = {};

      if (filteredLetters.length === 0) {
        setNoAlphabets(true);
      }

      filteredLetters.forEach((char) => {
        !frequencyDictonary[char]
          ? (frequencyDictonary[char] = 1)
          : frequencyDictonary[char]++;
      });

      // convert from key:val object to nested array and sort by descending frequency: ex: {a:1, e:3} to [[e,3], [a,1]]
      frequencyDictonary = Object.entries(frequencyDictonary).sort(
        (a, b) => b[1] - a[1]
      );

      setLetterCount(frequencyDictonary);
    }
  };

  const sortByAlpha = () => {
    setSortedByAlpha(letterCount.sort());
    setSortedByFreq("");
  };
  const sortByFreq = () => {
    setSortedByFreq(letterCount.sort((a, b) => b[1] - a[1]));
    setSortedByAlpha("");
  };

  const textGenerator = async () => {
    let randomQuote = await fetch("https://api.quotable.io/quotes/random");
    let randomQuoteJSON = await randomQuote.json();
    setAutoGeneratedWords(randomQuoteJSON[0].content);
    setWords(randomQuoteJSON[0].content);
  };

  return (
    <div className="mainClass">
      <div className="inputSide">
        {autoGenerated ? (
          <textarea rows="10" cols="30" value={autoGeneratedWords}></textarea>
        ) : (
          <textarea
            rows="10"
            cols="30"
            onChange={(e) => {
              setWords(e.target.value);
              setEmptyTextArea(false);
              setNoAlphabets(false);
            }}
            placeholder="Enter text here..."
          ></textarea>
        )}

        <div className="btnsDiv">
          <button
            className="analyzeBTN"
            onClick={() => {
              textProcessor(words);
              setAutoGenerated(false);
            }}
          >
            Analyze
          </button>

          <button
            className="generateBTN"
            onClick={() => {
              setAutoGenerated(true);
              textGenerator();
              setEmptyTextArea(false);
              setNoAlphabets(false);
              setLetterCount("");
            }}
          >
            Generate
          </button>
        </div>
      </div>
      <hr />
      <div className="outputSide">
        {letterCount && !noAlphabets ? (
          <Table
            tableData={letterCount}
            sortByAlpha={sortByAlpha}
            sortByFreq={sortByFreq}
          />
        ) : null}
        {noAlphabets ? (
          <div style={{ color: "blue" }}>No english letters found!</div>
        ) : null}
        {emptyTextArea ? (
          <div style={{ color: "red" }}>Please insert some text!</div>
        ) : null}
      </div>
    </div>
  );
};

createRoot(document.getElementById("root")).render(<App />);
// export default App;
module.exports = {
  x: App,
};
